# 配置端口
server:
  port: 8080
  servlet:
    context-path: /csr-api

spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.13.60.5:3306/csr?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    name: csr
    username: root
    password: 123456
    # 监控统计拦截的filters
    filters: stat,wall,log4j2
    # 配置初始化大小/最小/最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 获取连接等待超时时间
    maxWait: 60000
    # 间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    # 一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'X'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache,并且指定每个连接上的PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 50000

## 关闭安全验证
#management:
#  security:
#    enabled: false

mybatis-plus:
  configuration:
    cache-enabled: false

logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        security: debug
    com:
      project:
        csr: debug

jwt:
  security:
    path: /auth
    header: Authorization
    secret: secret
    expiration: 604800